title: South Asian Diasporas Notes
description: A compilation of notes from the South Asian Diasporas course taught by Professor Smitha Radhakrishnan at Wellesley College
baseurl: "/s23-south-asian-diasporas"
url: "https://intermezzio.me"

remote_theme: just-the-docs/just-the-docs
